apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:8443
  name: vcluster-demo-api-20260203-163747-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-163747-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-163747
current-context: vcluster-demo-api-20260203-163747
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRFFOY3ZEOTR6L0F3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRNMk9URTRNQjRYRFRJMk1ESXdNekUyTkRFMU9Gb1hEVEkzTURJdwpNekUyTkRFMU9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJelpQWGJFYTFmQ1BoNHEKdUI0blppSEowUk8vUGJZRDBTeld3V0JES0V1ZU1mQnpWeGxhK2tUL3BFcnkxc3pTTDlBWXRRRVd2clJRZHJhZgpyVWE3WXdHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXh1YldGZWsxdHZKdGpUSENaMzltUUNQN1NYekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBaWlWS1NxR2ZkZ1JUVFpNSDBoVGdFWnRxcFhyWnhYL2NCREI2K1NyTUFPUUloQUpJWWw2cUlWVzhtdTd5Vgo4c2trcURtQ2tvL0FyWCtqMEp6d21yS1hXZ21uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE16WTVNVGd3SGhjTk1qWXdNakF6TVRZME1UVTRXaGNOTXpZd01qQXhNVFkwTVRVNApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE16WTVNVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSYktrNkIxTkJacWVCc1hhZEV6MkU4T0d3UW5VSjcwUld2bmVLajhTQW8KMldTRVkxWnVMZXYxNWVmNmJuWkU1a2U1cUdlb1NTNWlCVFE0bWFOd0lZS2dvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU1ibTFoWHBOYmJ5YlkweHdtZC9aCmtBaiswbDh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBxY1JRTFExU1J1UkN0Y0h2QTdrTjN3MWQxbmxPdlgKOHZ5Z2J5N3ovUSttQWlCbEtoYUFqeHZxd1UrZVFvdXhQQVhsK0xMTEwrUGpvTGtXZWhhbXkrRVRBZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBaa21NSVhFMlYxMjR4RlNhV005NHpsdmNpaXJ5c0kzQUpUZTBHUUJZMmRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFak5rOWRzUnJWOEkrSGlxNEhpZG1JY25SRTc4OXRnUFJMTmJCWUVNb1M1NHg4SE5YR1ZyNgpSUCtrU3ZMV3pOSXYwQmkxQVJhK3RGQjJ0cCt0UnJ0akFRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
