apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:8443
  name: vcluster-demo-api-20260203-184102-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-184102-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-184102
current-context: vcluster-demo-api-20260203-184102
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJQVIxSmZLcExBQnd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRRME1EWTRNQjRYRFRJMk1ESXdNekU0TkRFd09Gb1hEVEkzTURJdwpNekU0TkRFd09Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJENWZ0d2ZGNytuL0FVUmsKK2Zwc244UTVGYTZ4YTQ1Z1JaTmx3SG85QzFrbEpJV3o5MW5Xc1YvZXN0OFM3ZGxtMW9RT3pRYlFQK1VacE5mUwpzcnNMZVFPalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU1AyQnhkL0FFM1VQK3dpQVJKNWtEUDR1MzA4ekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBRzIzdTdFZXJhK3U0SmxONkJZdzROQWFPekhnaEppeTl1MVRhN1Y2R29UQUlnSkRMN0ErOVBJSk1MOWVxdQpkR1lLcURzUzh2Z1RyaTd1bTVWNHQreWhYamM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE5EUXdOamd3SGhjTk1qWXdNakF6TVRnME1UQTRXaGNOTXpZd01qQXhNVGcwTVRBNApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE5EUXdOamd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRa21iMm9zdzJ2b1RmN1FOcGxobXVaTFRBWEZ2aDhaclh5RlRCYnBoTjkKSFNpQlhoQ0dKaXgzdmhLREFpMUZ0a2Q4b2pxR2lMSVRnNjZ5SzhsekxvNUJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWo5Z2NYZndCTjFEL3NJZ0VTZVpBCnorTHQ5UE13Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnUng1aDN0Y2JDVk5KdmEvMlh6WGYxdWZXQkdvSzBIdFIKeWlvK2VQVWs2dkFDSVFETW9UaTMrbXgxQWdHZ1gwcjgza2VkNzFYV1d4Q1poYVdFZHNlbER6YjR2UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZRSUJKWXJFYUdlSWJWR2ppSFFXVnFrYXZ4ci9LVy9NWTNVMTdFZHZTYitvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUGwrM0I4WHY2ZjhCUkdUNStteWZ4RGtWcnJGcmptQkZrMlhBZWowTFdTVWtoYlAzV2RheApYOTZ5M3hMdDJXYldoQTdOQnRBLzVSbWsxOUt5dXd0NUF3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
