apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:38599
  name: vcluster-demo-api-20260203-191126-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-191126-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-191126
current-context: vcluster-demo-api-20260203-191126
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJYy9WOTVRcjJrUU13Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRRMU9Ea3pNQjRYRFRJMk1ESXdNekU1TVRFek0xb1hEVEkzTURJdwpNekU1TVRFek0xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQZlpoTEc4WkdwSlozMmkKdCswRmVKRXJPVHh4Y0xyQlI3UllPRlhEWEp4YXhPMmhsa3RKYk5aUGhoZjB0NjNyZkJpRHVrUzl3TUx6UkhuUgpCb2IzRVgralNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUzhhYnNRTU1GVms1NEhCMzE2OElZU1dOZW5SekFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXI4WEo3ZE15RHVFck1pWGtydk1RUklNSnFNa3BHWWp1aFVqMjE4bTg1K0FDSVFDU1p0aXRDeGI4VFhEOQpna01ickN3WGg0MnNjNUlEejU3WDE0UENZL2Exdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM056QXhORFU0T1RNd0hoY05Nall3TWpBek1Ua3hNVE16V2hjTk16WXdNakF4TVRreE1UTXoKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM056QXhORFU0T1RNd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUU1nTlBlVUF4dm00N0JKVGlhazZlMWtNMWEydFNuUE9HWlRod0pXWVdECm1FR2lBT0t1L2JrbFNoY0Z4U3RGWWhjcE91eWZJM2xFdlRnQVcvNkNyZmFMbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV2R203RUREQlZaT2VCd2Q5ZXZDRwpFbGpYcDBjd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ05EMmhxc1YyNUJLRUpqcUZRbHRxOWQ0M1kzcUFTdkpCCklvdXI1RGsxZG9RQ0lRRFZHOXkyek5LWE9lSlZVTlYreUVDVmVONXBHRy9Va2pOL09pMmpNcWY2eUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFyN3Q5L2dWL1hSUzh3L05XRGNpaGZidjd1RUh4U1BXT1phY1VOeVpZc0dvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOTltRXNieGtha2xuZmFLMzdRVjRrU3M1UEhGd3VzRkh0Rmc0VmNOY25GckU3YUdXUzBscwoxaytHRi9TM3JldDhHSU82UkwzQXd2TkVlZEVHaHZjUmZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
