apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:48257
  name: vcluster-demo-api-20260204-203433-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260204-203433-cluster
    namespace: null
    user: user
  name: vcluster-demo-api-20260204-203433
current-context: vcluster-demo-api-20260204-203433
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJSGRubzloRHR3REl3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TWpNM01qZ3lNQjRYRFRJMk1ESXdOREl3TXpRME1sb1hEVEkzTURJdwpOREl3TXpRME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOV3h0ZGJrVG1RSzdvbGMKK0xqSXMzcnB2TlZ1UFNZK1hTZWo0akU2d1B0Sk54OFRhbWpvakRIajlVektTMEd1ZitOdkI3Q1dJckkweks3QQpVQ2NnaW0yalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGJZTHVaMlkyeUl4ODROeWVBbU51bFhUU2dNVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXR0SS9tUjREbEU2bjJrSHJlcm9vYUtpdUo2WU5ESk5XQ3ZYU3I2cnMxQXNDSVFDTW11SzZMckxBcXZvbgpKRko5RFNsaGNmS2NPOWNFUVZHMVVoL2NFQ2JwWlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM056QXlNemN5T0RJd0hoY05Nall3TWpBME1qQXpORFF5V2hjTk16WXdNakF5TWpBek5EUXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM056QXlNemN5T0RJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUzI2aVlnRVZuUTJESkpiWm9NTTQwM1hEc09zQ3ptY01VcjdCdm9QeTRMCkFUaXI0TytaZnMwOUM3SmJkREF5M1NacjV5RFFXOGhhUVFPSkNVd0lSbUI5bzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUyMkM3bWRtTnNpTWZPRGNuZ0pqYgpwVjAwb0RFd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1lLYzZrTXU3QXJUaHRMd0RuL0wrWGp4cDZiK3B3Mmp0CnEvUXVqZi9RanJ3Q0lRQzlkeUxmVEFKdVZiVFZVOWJKY1hTRHBmWGhGc2FNNEVEVk53R1pqK1pTSkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVwdzRjNXMyaVB6N0F1OXk0eW9NdjI5a0xsNDVIT05wc2ZSc2NXc0hEdUhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMWJHMTF1Uk9aQXJ1aVZ6NHVNaXpldW04MVc0OUpqNWRKNlBpTVRyQSswazNIeE5xYU9pTQpNZVAxVE1wTFFhNS80MjhIc0pZaXNqVE1yc0JRSnlDS2JRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
