apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:49889
  name: vcluster-demo-api-20260204-203601-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260204-203601-cluster
    namespace: null
    user: user
  name: vcluster-demo-api-20260204-203601
current-context: vcluster-demo-api-20260204-203601
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRDFKNVRvNi84UnN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TWpNM05ESTNNQjRYRFRJMk1ESXdOREl3TXpjd04xb1hEVEkzTURJdwpOREl3TXpjd04xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQY3dicXVSRTluRWFnSloKYStpTEp6bENKMUluWGhFK2Z4UDlUZEJnb1FZaWFUSm5nUEd6OEhYWC9HWnRCS2IrY0VuUE5iY0IzUXFONTcvQQpLZGYzUlc2alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUk40c0VWVkxobUNaL2pvQzd5VmFtMHUvVlEwREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQXdRdklacGYydlJBYWNNR2FtMGpXQXBlNDNxTDVEMGxlUUU5NUV3WnM4RG9DSUducjQrWnYyRFRiUTRDeQpWRUxGSC9XTTU0b1kzZFlPTXlEaDFyVEZ6RkZjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeU16YzBNamN3SGhjTk1qWXdNakEwTWpBek56QTNXaGNOTXpZd01qQXlNakF6TnpBMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeU16YzBNamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRN3gzR0hTemVsTHFMYVhiQnlscXFYeUxld0V3VkxaSlNKOGxUcC9HMUIKZmlzZitHS21mQ0ZpeFgxL054Z29aeTZ4NE94T0dveWlHa0pSY0Z3c3UxQ2xvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRlTEJGVlM0WmdtZjQ2QXU4bFdwCnRMdjFVTkF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYjVrU1ZPSlBSRXFMY0FsZGlKamlDMjAvdTE0LzZFWHEKaWhnVTRITkovQmdDSUQxRndJYzRucnhFbVhjdVJyRVhhZldIWng5R3d5SzAybzNXaWxjT04xZFIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpKU1RyUm84bTg5RytVVG5VVUhpdElOMUQ4RXVqZDZKOFRHOFVEcm1abUNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOXpCdXE1RVQyY1JxQWxscjZJc25PVUluVWlkZUVUNS9FLzFOMEdDaEJpSnBNbWVBOGJQdwpkZGY4Wm0wRXB2NXdTYzgxdHdIZENvM252OEFwMS9kRmJnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
