apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:46541
  name: vcluster-demo-api-20260203-191803-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-191803-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-191803
current-context: vcluster-demo-api-20260203-191803
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJUG45QjNNYndndUl3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRRMk1qZzVNQjRYRFRJMk1ESXdNekU1TVRnd09Wb1hEVEkzTURJdwpNekU1TVRnd09Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBcFFxbUNqYk5MY0pBNEMKa0hzSEZ4QnFQK21US25Ob2p2QjhvSjQ2NFF1MHFlK3RqNkpIV2d5OGUzWXFYNVVBaXArTnlnWFl6S3lNVjh3RQpMQXoyRlVxalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUk1tY1lzZWRidDdlMFViZWpUdDlpOHJLTFdiVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBYytqOVo3MFJiSmRnQlJhbXN1ekJnYlFPZTZDckZCMjdFSUdOVEZJSlJrUUloQVBJL0VHWXdhMlVRVWJ0ZAplazI3c0ozT1phNnZTTVE3enA3SllYRXUyaHk5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE5EWXlPRGt3SGhjTk1qWXdNakF6TVRreE9EQTVXaGNOTXpZd01qQXhNVGt4T0RBNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE5EWXlPRGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSRXlVRnphRzBRelBVQm5RSTVLeW1DRmdUc3RBa3FnUlYyVVA3aXJmdGoKS3dsZ1orUE5ZQnVrNDNTZmhieTBLa05NWUZkb1l2L1NQbTI2TzZLK1lyc3hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRKbkdMSG5XN2UzdEZHM28wN2ZZCnZLeWkxbTB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnV1pFcEJYQXR6c0RaOExNc2hldnZjbkhrVmtjVEZ0VnkKSDlmZjUrTEhsZEVDSVFEazQvZXpOKzBzR2I1dVdxc044ckNOc1FKcWZXc2orRm1QYzFZb3I5Um0ydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpORmovUVAzMEVKSU5ncDVUY2owMy9kekhaUUg5WFV2M0NZUlJpL3JuQmVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQ2xDcVlLTnMwdHdrRGdLUWV3Y1hFR28vNlpNcWMyaU84SHlnbmpyaEM3U3A3NjJQb2tkYQpETHg3ZGlwZmxRQ0tuNDNLQmRqTXJJeFh6QVFzRFBZVlNnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
