apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:45659
  name: vcluster-demo-api-20260203-185511-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-185511-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-185511
current-context: vcluster-demo-api-20260203-185511
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJWWt0cThJVkdWYXd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRRME9USXhNQjRYRFRJMk1ESXdNekU0TlRVeU1Wb1hEVEkzTURJdwpNekU0TlRVeU1Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHaVV4T08wdVNKbDBPWWoKWkFtOW9wTUVEdEw1cjdIUnRIblljS0lMaXJlb21DRGltRjlIVGI4R09DZ3NlbGtZaW1qYXpyQlJRNDM4TlRFaAprY0FrM3d5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVHFqbzFyT0ltZ05ZUzVYRm5hTlRZL294dXZvVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBamR3UkpDK0p0T1c2RDlPVWNuNWg5YTRaSFNnKzRyWkFTa3ZSdUJEbXpBUUloQU1XMHZIdHB2cmZMVFBkbAozMUg3MFZOZDByb09BWjNLOFl6dG9tdFNvSzhoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE5EUTVNakV3SGhjTk1qWXdNakF6TVRnMU5USXhXaGNOTXpZd01qQXhNVGcxTlRJeApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE5EUTVNakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVHA0NFRwQXdNQXFlODAvUVR5V2FXZFUxcE53Y2NBV2d2cFpCcnFCUmIKVEhNK2c5d0tHMDRuL09UZm1OajRLa1pUYTU0TzVtNEtNU2s0d0FVLzd2TmNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTZvNk5hemlKb0RXRXVWeFoyalUyClA2TWJyNkV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnREJINnB6dkNLbVpqcU9LOVNiMndLT0N5dDFyMHFMTmgKM3NEZXFvMTVFclFDSUh0QnNUQjdRSjFnNUQ1OUlFWmY2cDBQUllRMENWRDkvOXFaMUo3czBUMTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVLTmEzSStDUHNtckNPbzdzYXlTU3Bqa3lsNmVYbmwydmRlOFhWWEFVUVFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYUpURTQ3UzVJbVhRNWlOa0NiMmlrd1FPMHZtdnNkRzBlZGh3b2d1S3Q2aVlJT0tZWDBkTgp2d1k0S0N4NldSaUthTnJPc0ZGRGpmdzFNU0dSd0NUZkRBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
