apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:58685
  name: vcluster-demo-api-20260203-213142-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-213142-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-213142
current-context: vcluster-demo-api-20260203-213142
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJV0dUNXJlMXM0bGN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRVME16RXhNQjRYRFRJMk1ESXdNekl4TXpFMU1Wb1hEVEkzTURJdwpNekl4TXpFMU1Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJTVg3c1p5UlhHUDBxZW0KUklPQWU0SDgxNjNVZXRmaCtQeTdSbFZnWVllOGVkbzlGeTVHMlZOTUFiWDYvaWdMa0hldkE0OVV0ZC83MktwTApzWE9sS2oyalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUlZoaFlQS09jMVYxQVFCakUxN3FLSTZKUFBLakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTBFcjRJa2dFUXVZakdKcEpXb0ZyVzFoR05lVzRwRTlsNWtPVFFEZ2c4RU1DSUVObnUwY2tYek5TZjhVNApwdlhhTVBWck1XU1ZzWnc5b1Z0UG5LVUJuQzg1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE5UUXpNVEV3SGhjTk1qWXdNakF6TWpFek1UVXhXaGNOTXpZd01qQXhNakV6TVRVeApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE5UUXpNVEV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTZVcya0R3QzdjSjNSUUFUb1JHZ3NZRkJrbTlrN293d2R1L2E0L2VhSXgKZDhpeklSd202SkMxQVdDRWlWZnFuZVF2TldwOVFkdFdlVENNNWl1Umo2OERvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVZZWVdEeWpuTlZkUUVBWXhOZTZpCmlPaVR6eW93Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVU0vUGZGY1RQRUgyU0w0OEVZL1NjdTBQdWpHc01BNHAKNDJYekdmRGJWVElDSURpYml6WUFBb3FIU2Y0UE1XaHFDWEpldkxUV3VqZEc3Nlh0U1RmK3RJU2oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFMdmUxR2dzNEhNS1JpNTJrY0JkMUxFL0ZvRUtyQWxOYnVjTUZ0RGFWRE5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZ3hmdXhuSkZjWS9TcDZaRWc0QjdnZnpYcmRSNjErSDQvTHRHVldCaGg3eDUyajBYTGtiWgpVMHdCdGZyK0tBdVFkNjhEajFTMTMvdllxa3V4YzZVcVBRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
