apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mohammed-emad/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Feb 2026 18:37:13 EET
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    insecure-skip-tls-verify: true
    server: https://localhost:37869
  name: vcluster-demo-api-20260203-221051-cluster
contexts:
- context:
    cluster: vcluster-demo-api-20260203-221051-cluster
    namespace: default
    user: user
  name: vcluster-demo-api-20260203-221051
current-context: vcluster-demo-api-20260203-221051
kind: Config
users:
- name: user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJY2hIVG85UnA2ekV3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemN3TVRVMk5qWXdNQjRYRFRJMk1ESXdNekl5TVRFd01Gb1hEVEkzTURJdwpNekl5TVRFd01Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDT1RKR0ZVQTZTMXc1RHUKMG0reHBhcXJLcjYxSmhrdXc0UkRpRytvSUNINEh4dzg4eTVYeXBCdnMzY3F2eG1acml3MVdramZweGpxQXNGZgo2U28zcWd5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUVBYNTVkMmFjVDNDMDBtVldROFJ4TG9PUjJlREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBUkxVVEY5VTlpN2pnclByOUZmSHVBTlFBbjU0T2hyNUliaG8xelI0VWZ4UUloQUpYMm4wUWhhNzFTVml1dgphT2krVzNPWEdJZlZlT1oxMkRJbFJSdFhycHc0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpBeE5UWTJOakF3SGhjTk1qWXdNakF6TWpJeE1UQXdXaGNOTXpZd01qQXhNakl4TVRBdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpBeE5UWTJOakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRaG1GRzBPYlpCbXp1MFpaekZ3SHYxaUJWOG8wZUF0dlhkRlNYWEhrTkQKZnF3U3lZdThla3JwUkV4ZXRIcDJBZWNQY2dNbkNocVA1Y01CSzlQUTU3cHhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUQxK2VYZG1uRTl3dE5KbFZrUEVjClM2RGtkbmd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnWENDUitxV29QUUFiK0g1VjIramQvUlloRHQvMFdMZ1gKUFZRQzdiVkIyZkVDSVFEY0ZOMFFqWER3MUhFbHFMS0thUGV5K09oc2RSWGdKdkdWUWZqZHhSL2pnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlWaHorSVg3VkJ5V0VhaE1zSVZERzMzb3FEUVNzYkg0Z2lvLzViRVN0L2xvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSTVNa1lWUURwTFhEa083U2I3R2xxcXNxdnJVbUdTN0RoRU9JYjZnZ0lmZ2ZIRHp6TGxmSwprRyt6ZHlxL0dabXVMRFZhU04rbkdPb0N3Vi9wS2plcURBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
