{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aegis.fullname" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aegis.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aegis.serviceAccountName" . }}
    namespace: {{ include "aegis.namespace" . }}
{{- end }}
