{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aegis.serviceAccountName" . }}
  namespace: {{ include "aegis.namespace" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
